### ISSUE TITLE
Output formating on nested for loops

### ISSUE THREAD

**Issue by k4ch0** [cookiecutter/cookiecutter#1226]
* Cookiecutter version: Cookiecutter 1.6.0 (Python 3.6)
* Template project url: https://github.com/k4ch0/cookiecutter-molecule.git
* Python version: Python 3.6
* Operating System: Linux Mint 19.2

### Description:

Probably is more an jinja issue, but when I'm using a nested for loops I'm not able to format the output correctly:

Desire output:
```
platforms:
  - name: instance-centos7
    hostname: centos7
    image: centos/7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true
  - name: instance-1604
    hostname: ubuntu-1604
    image: ubuntu/xenial
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true
  - name: instance-1804
    hostname: ubuntu-1804
    image: ubuntu/bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
```
Wrong output:
```
platforms:
  - name: instance-centos7
    hostname: centos7
        
    image: centos/7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true- name: instance-1604
    hostname: ubuntu-1604
        
    image: ubuntu/xenial
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: true- name: instance-1804
    hostname: ubuntu-1804
        
    image: ubuntu/bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: true
    pre_build_image: trueprovisioner:
  name: ansible
```
Please noticed the spaces between hostname and image and the NO-space after pre_build_image

Here is the template that I'm using:
```
platforms:
  {% for i, j in cookiecutter.platforms|dictsort recursive -%}
    {% for k, l in j.items() -%}
      {% for m, n in l.items() -%}
  - name: {{ n.name }}
    hostname: {{ n.hostname }}
        {% if cookiecutter.molecule_scenario_name == "vagrant" -%}
    box: {{ n.vagrant_box }}
    memory: {{ n.vagrant_memory }}
    cpu: {{ n. vagrant_cpus }}
        {% else %}
    image: {{ n.docker_image }}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    privileged: {{ n.docker_privileged }}
    pre_build_image: {{ n.docker_pre_build_image }}
        {%- endif -%}
      {%- endfor -%}
    {%- endfor -%}
  {%- endfor -%}
```

and the cookiecutter.json file:

```
{
    "role_name": "Role Name",
    "role_name_slug": "{{ cookiecutter.role_name|lower|replace(' ', '-') }}",
    "role_description": "Role Description",
    "author": "Luis Cacho",
    "company": "Rackspace",
    "license": ["MIT", "GPLv3", "Apache", "Mozilla", "Unlicense"],
    "min_ansible_version": "2.7.12",
    "platforms": {
        "Ubuntu": {
            "versions": {
                "16.04": {
                    "name": "instance-1604",
                    "hostname": "ubuntu-1604",
                    "docker_image": "ubuntu/xenial",
                    "docker_privileged": "true",
                    "docker_pre_build_image": "true",
                    "vagrant_box": "ubuntu/xenial64",
                    "vagrant_memory": 4096,
                    "vagrant_cpus": 4
                },
                "18.04": {
                    "name": "instance-1804",
                    "hostname": "ubuntu-1804",
                    "docker_image": "ubuntu/bionic",
                    "docker_privileged": "true",
                    "docker_pre_build_image": "true",
                    "vagrant_box": "ubuntu/bionic64",
                    "vagrant_memory": 4096,
                    "vagrant_cpus": 4
                }
            }                
        },
        "CentOS": {
            "versions": {
                "7": {
                    "name": "instance-centos7",
                    "hostname": "centos7",
                    "docker_image": "centos/7",
                    "vagrant_box": "centos/7",
                    "docker_privileged": "true",
                    "docker_pre_build_image": "true",
                    "vagrant_memory": 4096,
                    "vagrant_cpus": 4
                }
            }
        }
    },
    "molecule_scenario_name": [ "default", "cicd","vagrant" ],
    "molecule_driver": [ "docker", "vagrant" ],
    "year": "{% now 'utc', '%Y' %}",
    "_copy_without_render": [
        "molecule/{{cookiecutter.molecule_scenario_name}}/Dockerfile.j2"
    ]

}
```

Please let me know any light on this.
