### ISSUE TITLE
Add support for a yaml filter

### ISSUE THREAD

**Issue by lieutdan13** [cookiecutter/cookiecutter#1246]
* Cookiecutter version: 1.6.0
* Template project url: N/A
* Python version: 3.7.3
* Operating System: Ubuntu 19.04

### Description:

I would like to generate a cookiecutter yaml config file into my project with all the options I have chosen, so that I can run cookiecutter again with the --config-file option at a later time.

### What I've run:
 I'd like to avoid doing something like this and have to add variables every time I add a new option:

{{cookiecutter.project_name}}/cookiecutter-options.yml
```
default_context:
    project_name: "{{ cookiecutter.project_name }}"
    app_name: "{{ cookiecutter.app_name }}"
    python_version: "{{ cookiecutter.python_version }}"
```

I'd rather be able to do this:

{{cookiecutter.project_name}}/cookiecutter-options.yml
```
{{ cookiecutter | to_yaml }}
```
OR
```
{{ cookiecutter | dump_config }}
```
