### ISSUE TITLE
Shouldn't cookiecutter be limited to the `cookiecutter` namespace?

### ISSUE THREAD

**Issue by UltiRequiem** [cookiecutter/cookiecutter#1659]
* Cookiecutter version: Cookiecutter 1.7.3 from /home/ulti/.local/lib/python3.8/site-packages (Python 3.8)
* Template project url: https://github.com/UltiRequiem/cookiecutter-javascript-module
* Python version: Python 3.8.10
* Operating System: linux

### What I've run:

```sh
cookiecutter https://github.com/UltiRequiem/cookiecutter-javascript-module
```

https://github.com/UltiRequiem/cookiecutter-javascript-module/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/cd.yaml#L7

In my continuous integration, I have 

```yaml
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

```

Cookiecutter is trying to resolve the third line and is falling because is not defined. That variable is supposed to be got while running the action.

Example of a project using it

https://github.com/UltiRequiem/timezones/blob/main/.github/workflows/cd.yaml#L7

Shouldn't be cookiecutter limited to the `cookiecutter` namespace? Any workaround?
