### ISSUE TITLE
_copy_without_render does not work properly

### ISSUE THREAD

**Issue by rdvansloten** [cookiecutter/cookiecutter#1817]
* Cookiecutter version: 2.1.1
* Template project url: Private
* Python version: 3.10.9
* Operating System: MacOS

### Description:

I have a Terraform Docs file inside my {{cookiecutter.module_name}} folder with this content;
```
formatter: markdown table

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}
    
    [//]: # (END_TF_DOCS)
```

And cookiecutter does not handle the `{{ .Content }}` line.

### What I've run:
```
"_copy_without_render": [
    "{{cookiecutter.module_name}}/.terraform-docs.yml"
]

"_copy_without_render": [
    "*/.terraform-docs.yml"
]

"_copy_without_render": [
    ".terraform-docs.yml"
]

Thinking maybe the leading period matters, I renamed the file, also did not work:
"_copy_without_render": [
    "terraform-docs.yml"
]
```
I have also tried wrapping it, to no avail: `${{ "{{" }} .Content {{ "}}" }}`

When using _copy_without_render:
```
  File "/opt/homebrew/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "terraform-docs.yml", line 12, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '.'
  File "terraform-docs.yml", line 12
    {{ .Content }}
```

When wrapping in multiple brackets:
```
Unable to create file 'pipelines/terraform-docs.yml'
Error message: 'parameters' is undefined
Context: {
    "cookiecutter": {
        "_copy_without_render": [
            "{{cookiecutter.module_name}}/.terraform-docs.yml"
        ],
```
