### ISSUE TITLE
Adding value to nested dicts broken after 2.2.0

### ISSUE THREAD

**Issue by jensens** [cookiecutter/cookiecutter#2009]
Tested with cookiecutter version: 2.5.0 and main

Prior to Version 2.2.0 one could have a `cookiecutter.json` with a dict as value like so:
```json
{
  "mainkey": {
    "subkey1": "value1"
    "subkey2": "value2"
   }
}
```
and then define an YAML to pass in with `--config-file ` like so:
```YAML
default_context:
    mainkey:
        subkey1: value1
        subkey2: value2
        subkey3: value3
        subkey4: value4
```
And after this, in the template with `cookiecutter.mainkey` one got all `subkey1` to `subkey4`.

The feature https://github.com/cookiecutter/cookiecutter/pull/1692 here broke this (even if there were already some other fixes to this).

After 2.2.0 all we got are `subkey1` and `subkey2`.
