### ISSUE TITLE
Add aliases for cookiecutters

### ISSUE THREAD

**Issue by pfmoore** [cookiecutter/cookiecutter#246]
Remembering the locations of cookiecutters can be a bit of a pain - even if it's just including the local path.

It would be useful to have an extra section in `cookiecutterrc` for aliases to cookiecutter locations. Something like:

```
aliases:
  python: https://github.com/audreyr/cookiecutter-pypackage
  django: https://github.com/marcofucci/cookiecutter-simple-django
  docs: ~/samples/templates/documentation
```

The code would simply need to translate an alias into a path before doing any of the existing processing.
